### ISSUE TITLE
Any updates coming?

### ISSUE THREAD

**Issue by CaptainMalReynolds** [ackyshake/Lyrical#1]
Hi there, I bought this app few years ago and it wasn't updated for the last couple of years. Widget stopped working, and the app not always running as expected. 
Are there any updates coming for the app to be able to use lyrics widget in the newer Mac OS like Monterey etc?
Thanks

**Comment by ackyshake** [comment]
Hey there! 

Unfortunately, Apple has overhauled how the widgets work starting from Mac OS 11, so currently it's not an easy task to have lyrics showing up as a widget (you'd need a scroll view or an expandable box, both of which aren't supported in the current Notification Center). 

So as stated in the description, I made a choice to stop developing Lyrical and open source it.

The last release that Lyrical works successfully is El Capitan (Mac OS 10.11).
